# Generated by Django 6.0 on 2025-12-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('CUSTOMER', 'تجهیز مشتری (تحت کالیبراسیون)'), ('REFERENCE', 'تجهیز مرجع (استاندارد آزمایشگاه)')], default='CUSTOMER', max_length=20, verbose_name='دسته تجهیز'),
        ),
    ]
