# Generated by Django 6.0 on 2025-12-30 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پیشنهادی مشتری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات مشتری')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('CANCELED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='assets.equipment', verbose_name='تجهیز')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده')),
            ],
            options={
                'verbose_name': 'درخواست کالیبراسیون',
                'verbose_name_plural': 'درخواست\u200cهای کالیبراسیون',
            },
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ برنامه\u200cریزی شده اجرا')),
                ('status', models.CharField(choices=[('ASSIGNED', 'تخصیص یافته'), ('IN_PROGRESS', 'در حال انجام'), ('REVIEW', 'در انتظار بازبینی فنی'), ('COMPLETED', 'تکمیل شده')], default='ASSIGNED', max_length=20, verbose_name='وضعیت اجرایی')),
                ('technician_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای تکنسین')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_order', to='operations.calibrationrequest', verbose_name='درخواست مرتبط')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین مسئول')),
            ],
            options={
                'verbose_name': 'سفارش کار (Job Order)',
                'verbose_name_plural': 'سفارش\u200cهای کار',
            },
        ),
    ]
