# Generated by Django 6.0 on 2025-12-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='مثلاً 23.5', verbose_name='دما (°C)')),
                ('humidity', models.FloatField(help_text='مثلاً 45', verbose_name='رطوبت (%)')),
                ('calibration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اجرا')),
                ('technical_notes', models.TextField(blank=True, verbose_name='یادداشت فنی')),
                ('final_verdict', models.BooleanField(default=True, verbose_name='آیا قبول است؟ (Pass)')),
                ('job_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='operations.joborder', verbose_name='سفارش کار مرتبط')),
                ('reference_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibrations_performed', to='assets.equipment', verbose_name='تجهیز مرجع استفاده شده')),
            ],
            options={
                'verbose_name': 'نتیجه کالیبراسیون',
                'verbose_name_plural': 'نتایج کالیبراسیون',
            },
        ),
        migrations.CreateModel(
            name='MeasurementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_value', models.FloatField(verbose_name='مقدار مرجع/نمی (Nominal)')),
                ('measured_value', models.FloatField(verbose_name='مقدار خوانده شده (Measured)')),
                ('error', models.FloatField(blank=True, null=True, verbose_name='خطا')),
                ('uncertainty', models.FloatField(blank=True, null=True, verbose_name='عدم قطعیت')),
                ('calibration_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='operations.calibrationresult')),
            ],
            options={
                'verbose_name': 'داده اندازه\u200cگیری',
                'verbose_name_plural': 'داده\u200cهای اندازه\u200cگیری',
            },
        ),
    ]
