# Generated by Django 6.0 on 2025-12-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('operations', '0002_calibrationresult_measurementresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationresult',
            name='reference_standard',
            field=models.ForeignKey(limit_choices_to={'category': 'REFERENCE'}, on_delete=django.db.models.deletion.PROTECT, related_name='calibrations_performed', to='assets.equipment', verbose_name='تجهیز مرجع استفاده شده'),
        ),
    ]
